extends:
  - airbnb
  - airbnb-typescript
  - next/core-web-vitals
  - prettier
rules:
  react/function-component-definition: off
  react/jsx-props-no-spreading: off
  react/require-default-props: off
  jsx-a11y/anchor-is-valid:
    - error
    - components:
        - Link
      specialLink:
        - to
      aspects:
        - invalidHref
        - preferButton
overrides:
  - files:
      - '**/*'
    parser: '@typescript-eslint/parser'
    parserOptions:
      project: ./tsconfig.json
      warnOnUnsupportedTypeScriptVersion: false
