root: true
plugins:
  - tsdoc
extends:
  - airbnb
  - airbnb-typescript
  - plugin:unicorn/recommended
  - next/core-web-vitals
  - plugin:eslint-comments/recommended
  - prettier
rules:
  consistent-return: off # When enabled, it makes it impossible to use early returns without explicitly returning undefined
  react/jsx-props-no-spreading: off # Prop types already protect against passing invalid or unnecessary props down to components.
  react/require-default-props: off # This rule doesn't play well with TypeScript.
  import/no-extraneous-dependencies: off # pnpm already prohibits extraneous dependencies.
  unicorn/filename-case: off
  unicorn/prevent-abbreviations:
    - error
    - allowList:
        props: true # Allow 'props' as an abbreviation since it's a common React convention.
  eslint-comments/require-description: error # Prevents disabling eslint rules without providing a reason.
  tsdoc/syntax: error
overrides:
  - files: './src/app/**/route.ts'
    rules:
      import/prefer-default-export: off # Route handlers must be exported as named exports to work.
parserOptions:
  project: ./tsconfig.json
