root: true
extends:
  - airbnb
  - airbnb/hooks
  - airbnb-typescript
  - plugin:unicorn/recommended
  - next/core-web-vitals
  - turbo
  - prettier
rules:
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
  react/jsx-props-no-spreading:
    - error
    - html: enforce
      custom: enforce
      explicitSpread: ignore
      exceptions:
        - Component
        - ClerkProvider
  unicorn/filename-case: off
  unicorn/prevent-abbreviations:
    - error
    - allowList:
        props: true
overrides:
  - files: './{src,test}/**/?(*.)+test.{tsx,ts}'
    extends:
      - plugin:jest/recommended
      - plugin:jest-dom/recommended
      - plugin:testing-library/react
parserOptions:
  project: ./tsconfig.json
