root: true
extends:
  - airbnb
  - airbnb/hooks
  - airbnb-typescript
  - plugin:unicorn/recommended
  - next/core-web-vitals
  - prettier
rules:
  react/function-component-definition:
    - error
    - namedComponents: arrow-function
      unnamedComponents: arrow-function
  react/jsx-props-no-spreading:
    - error
    - html: enforce
      custom: enforce
      explicitSpread: ignore
      exceptions:
        - Component
  unicorn/filename-case:
    - error
    - cases:
        camelCase: true
        pascalCase: true
overrides:
  - files: './src/**/?(*.)+test.{tsx,ts}'
    extends:
      - plugin:jest/recommended
      - plugin:testing-library/react
parserOptions:
  project: ./tsconfig.json
