name: Development

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:
    inputs:
      environment:
        description: 'The environment to build for'
        required: true
        type: string
    secrets:
      vercel-organization-id:
        description: 'The Vercel organization id'
        type: string
      vercel-project-id:
        description: 'The Vercel project id'
        type: string
      vercel-token:
        description: 'The Vercel token'
        required: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Lint
        run: pnpm lint

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Test
        run: pnpm test

  build:
    name: Build
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.vercel-organization-id }}
      VERCEL_PROJECT_ID: ${{ secrets.vercel-project-id }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Pull Vercel environment information
        run: pnpm vercel pull --yes --environment=${{ inputs.environment }} --token=${{ secrets.vercel-token }}

      - name: Build application
        run: pnpm vercel build ${{ inputs.environment == "production" && "--prod" }} --token=${{ secrets.vercel-token }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: .vercel/output
